### ISSUE TITLE
商城页面加载问题

### ISSUE THREAD

**Issue by caozeyou** [ShenShu2016/uwcssa_ca#121]
@Bubbrex 商城页面第二个图片加载不出来，https://uwcssa.ca/market/rental/707095c5-d892-4eaa-97ff-d2f3e2bff9a3
并且后退的时候到这个https://uwcssa.ca/market/rental/707095c5-d892-4eaa-97ff-d2f3e2bff9a3是空白，并且需要后退很多次才能有页面显示。

**Comment by Bubbrex** [comment]
这个问题的出现是因为打开商城二手商品的details的页面call API的时候，额外使用了一次async/await function，由于remove selected market item是在try/catch/finally block里的finally里，所以在快速由market item details页面切换到别的页面的时候，redux会没有remove selected item，这导致了进别的details的时候select market item里面的值不匹配，最终就报错页面加载不出来了。

现在把多余的async/await function删去，功能正常。
