### ISSUE TITLE
编辑个人信息弹出窗口问题

### ISSUE THREAD

**Issue by yingliangly** [ShenShu2016/uwcssa_ca#130]
编辑个人信息弹出窗口后，滚动条显示不是从最顶端开始，所以用户可能忽略滚动条上方内容☺。

**Comment by yingliangly** [comment]
![捕获](https://user-images.githubusercontent.com/94273021/141667301-b7167306-c639-4625-a715-223f589df44a.PNG)

**Comment by yingliangly** [comment]
教育经历，工作经验的滚动条有类似的问题。
![捕获3](https://user-images.githubusercontent.com/94273021/141668456-ce3b8125-85af-43f5-8111-54e53a179c39.PNG)
![捕获4](https://user-images.githubusercontent.com/94273021/141668462-e9d2231f-8985-425a-b9c3-a2e8785f4caf.PNG)

**Comment by ShenShu2016** [comment]
8a8e84a249a64cbd98012eee4eab8d25bc21d10b
fixed, because the TextField autoFocus will directly put on the input field.
