### ISSUE TITLE
教育经历资料未填完整时不能被成功保存

### ISSUE THREAD

**Issue by yingliangly** [ShenShu2016/uwcssa_ca#131]
![image](https://user-images.githubusercontent.com/94273021/141668175-668f222a-2f8f-45ba-9432-a3067496f913.png)
如果没有把信息填完整，点击保存后，信息不能被成功保存。

**Comment by ShenShu2016** [comment]
3ca0c7125ca1c2c2e1b957ad3a71093204d9f4cd
修复，并且增加了删除功能
