### ISSUE TITLE
二手商品信息的展示图片建议缩小一点

### ISSUE THREAD

**Issue by yingliangly** [ShenShu2016/uwcssa_ca#134]
https://uwcssa.ca/market/create/item
建议上传图片后的展示图可以缩小一点
![image](https://user-images.githubusercontent.com/94273021/141693078-e10446f0-afb2-480e-a554-40c6673199f6.png)

**Comment by ShenShu2016** [comment]
@Bubbrex

**Comment by ShenShu2016** [comment]
d94699857da510ae9afb351cda90b7f12a3b8c2e
fixed
Thanks @Bubbrex
