### ISSUE TITLE
dev.uwcssa.ca 登录后网页无显示

### ISSUE THREAD

**Issue by XiaoshuaiGeng** [ShenShu2016/uwcssa_ca#139]
# dev.uwcssa.ca 登录后网页无显示
- 页面路径: [https://dev.uwcssa.ca/account/dashboard/](https://dev.uwcssa.ca/account/dashboard/)
- 登录后点击个人资料之后网页无法正常显示

**Comment by ShenShu2016** [comment]
42244f7b08aa98cb6bf3212c86b54214f5cbfe04
fixed

**Comment by XiaoshuaiGeng** [comment]
![image](https://user-images.githubusercontent.com/33788705/142088296-04493656-6406-405b-9142-63b0daf318dc.png)
登录后无法进入dashboard
