### ISSUE TITLE
Event 持续时间有问题

### ISSUE THREAD

**Issue by ShenShu2016** [ShenShu2016/uwcssa_ca#181]
https://uwcssa.ca/event/29f7d260-73d3-4c7b-a58c-238cf67849c1

startDate(pin):"2021-11-20T17:00:21.000Z"
endDate(pin):"2022-11-20T23:55:27.343Z"

其中持续一年而不是 11月20号 17:00 - 23:55 
@shikaijin

**Comment by shikaijin** [comment]
Revised

**Comment by ShenShu2016** [comment]
5825025dc9849520a1d6b6dbff5dab30b1d16737
fixed
