### ISSUE TITLE
Invalid: 用户信息界面意见

### ISSUE THREAD

**Issue by ChangyeMa** [ShenShu2016/uwcssa_ca#214]
1. linkedin格式错误提示语“不能为空”应修改为“格式不对”
![image](https://user-images.githubusercontent.com/81818920/144762691-904d3611-fbbf-4d9b-886d-14000944ad8c.png)

2. 自我介绍，教育，工作中textfield添加字数限制
![image](https://user-images.githubusercontent.com/81818920/144762701-0e53b4a6-a60d-474f-8c85-a62352d22d4e.png)

3. 起始时间应该比结束时间早
![image](https://user-images.githubusercontent.com/81818920/144762709-31d91764-7352-42a3-8ec9-96a9bf168b06.png)

4. 教育栏分数可以填写负数，专业和介绍里可以单填写特殊符号
![image](https://user-images.githubusercontent.com/81818920/144762716-47ee9157-9b7a-441d-b695-432db0841c28.png)

5. 在填写格式不符合要求的时候没有相应的提示说明

6. 工作简介不能显示所有内容只有一行
![image](https://user-images.githubusercontent.com/81818920/144762722-c59774fc-ed53-4b4b-927c-93f5cf9ef43a.png)

**Comment by ShenShu2016** [comment]
@Bubbrex

**Comment by ShenShu2016** [comment]
6c604acd9fd3fe262d2200698a1fae1840135171
1，2，4，6 fixed
