### ISSUE TITLE
Bug：活动界面中正在的进行的活动显示“coming soon”

### ISSUE THREAD

**Issue by ChangyeMa** [ShenShu2016/uwcssa_ca#215]
需添加系统时间识别以判断活动是finished/in progress/coming soon
![image](https://user-images.githubusercontent.com/81818920/144762632-57c86cba-cbb3-4cf9-b81e-5a047f852abe.png)

**Comment by ShenShu2016** [comment]
@shikaijin

**Comment by ShenShu2016** [comment]
f5fbd899eb8baeba617166bf212298bf09746a30
fixed
