### ISSUE TITLE
商城卖家信息无法复制

### ISSUE THREAD

**Issue by ChangyeMa** [ShenShu2016/uwcssa_ca#217]
![image](https://user-images.githubusercontent.com/81818920/144762740-71f5429d-13bd-471b-b46e-d7ea10415a35.png)

**Comment by ShenShu2016** [comment]
@Bubbrex

**Comment by Bubbrex** [comment]
现在你hover上去会有提示你去复制。你点下去就可以复制了。

**Comment by ShenShu2016** [comment]
f7051871c91e8af326fb9a9803a4c8315de7d695

fixed
