### ISSUE TITLE
提高发布新闻、活动的权限

### ISSUE THREAD

**Issue by HHaiHH** [ShenShu2016/uwcssa_ca#235]
比如发布者可以选择本次活动具体需要的内容（如地址，姓名，email，电话，一些问卷式内容；以及这些问题必填or选填）
提高每个活动内容 在活动安排以及统计的实用性和flexible。

因为每套活动可能对应需要的信息不一致，如果每次都进行系统更改不太智能。

**Comment by ShenShu2016** [comment]
@shikaijin
